### ISSUE TITLE
QuickER Breaks /help

### ISSUE THREAD

**Issue by NotThorny** [Yuu-golang/QuickER#1]
https://github.com/c2tr-plugin/QuickER/blob/173e8d050705f4d04b94b3075882be700e2375fc/pom.xml#L31

Please update your dependency to 1.4.6 to fix this plugin breaking the `/help` command.

**Comment by c2t-r** [comment]
Thank you for letting me know. I forgot to change the version.
I think the current grasscutter is 1.4.5, is 1.4.6 ok?

**Comment by NotThorny** [comment]
1.4.6 is the latest version on sonatype, so setting the dependency jar to that version is best as it will be pulled from there automatically when building. Grasscutter actually updated to 1.4.6-dev as well, but usually one version ahead is just the 'release version' of x.y.z-dev, if that makes sense.

**Comment by c2t-r** [comment]
Thank you for fixing it! i now understand why 1.4.6 is ok.
